<a href="https://colab.research.google.com/github/danielarugeles1972-prog/ESTADISTICA-II/blob/main/bono_estadistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Bono acerca del manejo de Numpy y Pandas: Daniela Rugeles Rueda**

Manejo de módulos integrados

NumPy: se usa principalmente para trabajar con datos numéricos de forma rápida, eficiente y estructurada. Un objeto tipo NumPy es un arreglo base para hacer matemáticas y manipular datos en Python.

Pandas: es una librería diseñada para trabajar con datos estructurados, es decir, datos organizados en filas y columnas, como los que encontramos en tablas de Excel o bases de datos. Su estructura principal es el DataFrame, un objeto que permite cargar conjuntos de datos desde distintas fuentes, limpiarlos eliminando errores o valores vacíos, transformarlos según las necesidades del análisis, y extraer conclusiones a partir de ellos. Se utiliza especialmente cuando trabajamos con bases de datos relacionales, donde la información está distribuida en múltiples tablas conectadas entre sí.

 NumPy es una librería enfocada en el cálculo numérico eficiente mediante arrays multidimensionales, ideal para operaciones matemáticas rápidas, álgebra lineal y procesamiento de datos puramente numéricos; mientras que Pandas es una librería de más alto nivel diseñada para la manipulación y análisis de datos estructurados, como tablas tipo Excel o bases de datos, permitiendo trabajar con columnas con nombres, datos de distintos tipos, limpieza, filtrado y agrupación. En la práctica, Pandas se apoya internamente en NumPy, por lo que ambas se complementan y se utilizan juntas en la mayoría de flujos de ciencia de datos.

Carga de Paquete np de NumPy:

In [1]:
import numpy as np

Creando arreglos:

In [2]:
a = np.array([1, 3, 4, 5])
b = np.array([[1, 3], [4, 5]])
print(a)
print(b)

[1 3 4 5]
[[1 3]
 [4 5]]

In [6]:
a = np.array([1, 3, 4, 5])
b = np.array([[1, 3], [4, 5], [1, 4]])
print(a)
print(b)

[1 3 4 5]
[[1 3]
 [4 5]
 [1 4]]

In [20]:
b*2

array([[ 2,  6],
       [ 8, 10],
       [ 2,  8]])

In [22]:
lista = [2, 3, 5]

In [23]:
lista*2

[2, 3, 5, 2, 3, 5]

In [25]:
arr*2

array([2, 4, 6])

In [27]:
arr.shape #Forma (Dimensiones)

(3,)

In [ ]:
b.shape #Arreglo de tres componentes cada uno con dos elementos

(3, 2)

In [28]:
arr.ndim #Número de dimensiones

1

In [29]:
b.ndim #Número de elementos por cada componente

2

In [30]:
b.dtype #Tipo de dato

dtype('int64')

In [31]:
b.size #Cantidad de elementos en todas las componentes

6

Arreglos especiales:

In [32]:
np.zeros((3,4)) #Todo lleno de ceros: 3 componentes y 4 elementos por componente - Arreglo de ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((2,2)) #Todo lleno de ceros: 2 componentes y 3 elementos por componente - Arreglo de unos

array([[1., 1.],
       [1., 1.]])

In [37]:
np.eye(4) #La matriz identidad de una matriz cuadrada de tamaño 4- Arreglo de la matriz identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.arange(0, 8,3) #Del 0 hasta el 10 (sin tomar el 10), separado por 2

array([0, 3, 6])

In [12]:
np.linspace(0,1,5) #5 elementos equidistantes entre el 0 y el 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
arry = np.array([10, 20, 30, 40]) #Llamar la función del módulo
arry[0]

np.int64(10)

In [40]:
arry[-1]

np.int64(40)

In [41]:
arry[0:2] #Tomando de índice del 0 al 2 (sin tomar el 2)

array([10, 20])

Indexación de matrices:

Matri= (1 2 3
        4 5 6) y es nuestro objeto matemático
        
        Matri[0,1]=2

        Matri[:,1]=(1,4)

        Matri[1,:]=(4,5,6)

In [43]:
matri = np.array([[2,4,6],[1,3,5]]) #Definición de Matriz

In [44]:
matri[0,2] #El índice 1 de la ceroésima fila - Elemento 0,2

np.int64(6)

In [45]:
matri[:,2]

array([6, 5])

In [46]:
matri[:,0] #

array([2, 1])

In [49]:
matri[1,:]

array([1, 3, 5])

In [53]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
a + b
#Sumar componente a componente

array([ 3,  7, 11])

In [54]:
a*b
#Multiplicar componente a componente

array([ 2, 12, 30])

In [55]:
matri1 = np.array([[2,3,3],[4,5,6]]) #Definición de Matriz 1
matri1*matri #Producto de Hadamard es decir producto componente a componente

array([[ 4, 12, 18],
       [ 4, 15, 30]])

In [56]:
[x * 2 for x in lista] #Lento

[4, 6, 10]

In [57]:
arr * 2 #Rápido

array([2, 4, 6])

Funciones Estadísticas implementadas:

In [61]:
c=np.array([1.58, 1.60, 1.70, 1.62, 1.50, 1.90, 1.52])
print(np.mean(c), np.median(c), np.std(c), np.sum(c), np.min(c), np.max(c))
#Determina la media, la mediana, la desviación estándar, el total, el valor mínimo, el valor máximo

1.6314285714285715 1.6 0.1255193293513645 11.42 1.5 1.9

Manipulación de Arreglos:

In [63]:
d = np.array([1, 2, 3, 4, 5, 6]) #Cambiar formas
d.reshape(3,2)
#Inicialmente,tien seis componentes de un elemento cada una
#El primer argumento me dice el número de componentes, cambia a dos componentes cada una con tres elementos

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
np. concatenate([d, a]) #Concatenar arreglos, es decir a un arreglo le pego otro

array([1, 2, 3, 4, 5, 6, 2, 4, 6])

In [65]:
np. concatenate(d.reshape(2,3))

array([1, 2, 3, 4, 5, 6])

In [66]:
d.reshape(2,3).flatten() #Vectoriza la matriz

array([1, 2, 3, 4, 5, 6])

In [67]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]]) #Producto punto - Multiplicación de matrices

np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [68]:
np.linalg.det(a) #Determinante - Funciones de álgebra lineal y se calcula el determinante de una matriz

np.float64(-2.0000000000000004)

In [ ]:
np.linalg.inv(a) #Inversa de una matriz

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [69]:
np.linalg.matrix_transpose(a) #Traspuesta de una matriz

array([[1, 3],
       [2, 4]])

In [70]:
np.random.rand(10) #Números aleatorios entre cero y uno
#Es decir genera 10 valores aletarorios de una distribución uniforme en el intervalo (0,1)

array([0.11682082, 0.04646645, 0.96721549, 0.69665999, 0.1500396 ,
       0.01832741, 0.5935446 , 0.36251753, 0.83479309, 0.36718802])

In [71]:
np.random.randint(0,10) #Genera un valor entero entre 0 y el anterior al 10
#Un valor de la distribución uniforme discreta

0

In [72]:
np.random.randn(8) #Genera 8 valores aleatorios de una distribución normal con media 0 y
#Desviación estándar 1

array([ 0.23757807,  0.73822477,  0.24845108, -0.41691645,  0.03463431,
       -2.43138141, -0.60924329, -0.52440015])

In [73]:
e = np.array([1, 2, 3, 4, 5]) #Filtrado y condiciones
f = e[e > 3]
f

array([4, 5])

In [74]:
e[(e > 2) & (e < 5)] #Note que el y es así &. El o es así |

array([3, 4])

In [75]:
np.where(e > 3, 1, 0) #donde e > 3 anotamos un 1, y donde no, anotamos un 0

array([0, 0, 0, 1, 1])

In [76]:
np.where(e > 3, 1, e) #Los valores que no queremos reemplazar, anotamos el mismo objeto

array([1, 2, 3, 1, 1])

Ahora con Pandas

Importamos el paquete de Pandas

In [77]:
import pandas as pd

In [78]:
s = pd.Series([15, 25, 40]) #Vector columna
s
#Pandas es un objeto tipo tabla

0    15
1    25
2    40
dtype: int64

In [80]:
df = pd.DataFrame({ 'nombre': ['Luz', 'Andres', 'Miguel', 'Marta'],
                   'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá'],
                    'edad': [25, 32, 20, 28],
                    'salario': [1200, 2100, 2600, 3100]
                    }) #Creando data.frames y es un objeto tipo Diccionario
df

   nombre    ciudad  edad  salario
0     Luz    Bogotá    25     1200
1  Andres  Medellín    32     2100
2  Miguel      Cali    20     2600
3   Marta    Bogotá    28     3100

In [82]:
average_salary_by_city = df.groupby('ciudad')['salario'].mean()
display(average_salary_by_city)

ciudad
Bogotá      2150.0
Cali        2600.0
Medellín    2100.0
Name: salario, dtype: float64

In [83]:
df.head() #primeras filas
#Nos da los primeros 4 datos de nuestra base de datos

   nombre    ciudad  edad  salario
0     Luz    Bogotá    25     1200
1  Andres  Medellín    32     2100
2  Miguel      Cali    20     2600
3   Marta    Bogotá    28     3100

In [84]:
df.tail(2) #Últimas filas
#Nos muestras las dos últimas filas de nuestra base de datos

   nombre  ciudad  edad  salario
2  Miguel    Cali    20     2600
3   Marta  Bogotá    28     3100

In [85]:
df.info() #Tipo de datos
#Nos muestra cada una de las columnas, sí hay elementos nulos, es decir, datos faltantes y el tipo de objeto
#Los primeros objetos son cadenas, pueden ser texto o pueden ser elementos de tipo buleano

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nombre   4 non-null      object
 1   ciudad   4 non-null      object
 2   edad     4 non-null      int64
 3   salario  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [86]:
df.describe() #Estadísticas
#Que hace el método describe estadísticas descriptivas básicas para variables cuantitativas

            edad      salario
count   4.000000     4.000000
mean   26.250000  2250.000000
std     5.057997   810.349719
min    20.000000  1200.000000
25%    23.750000  1875.000000
50%    26.500000  2350.000000
75%    29.000000  2725.000000
max    32.000000  3100.000000

In [87]:
df.shape #(filas, columnas)
#El método shape nos dice el número de filas y el número de columnas que tiene mi base de datos

(4, 4)

In [88]:
salario_promedio = df['salario'].mean()
print( f"El salario_promedio: {salario_promedio}")
#

El salario_promedio: 2250.0

In [89]:
df['edad'] #Para imprimir la columna edad

0    25
1    32
2    20
3    28
Name: edad, dtype: int64

In [90]:
df[['nombre', 'edad']] #Selección de columnas, utilizando una lista con los respectivos nombres

   nombre  edad
0     Luz    25
1  Andres    32
2  Miguel    20
3   Marta    28

In [91]:
df[df['edad'] >25] #Selección de filas, es decir las personas que tengan más de 25 años

   nombre    ciudad  edad  salario
1  Andres  Medellín    32     2100
3   Marta    Bogotá    28     3100

In [93]:
df[(df['edad'] > 20) & (df['edad']  < 40)] #Las personas que tengan más de 20 años, pero que sean menores de 40 años

   nombre    ciudad  edad  salario
0     Luz    Bogotá    25     1200
1  Andres  Medellín    32     2100
3   Marta    Bogotá    28     3100

In [95]:
data = {
    'nombre': ['Aaron', 'Luisa', 'Sebastian', 'Ana', None],
        'edad': [25, np.nan, 32, 24, 45],
        'salario': [1500, 2100, None, 1200, 5500],
        'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali']
    }
data

{'nombre': ['Aaron', 'Luisa', 'Sebastian', 'Ana', None],
 'edad': [25, nan, 32, 24, 45],
 'salario': [1500, 2100, None, 1200, 5500],
 'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali']}

In [97]:
data1 = pd.DataFrame(data) #Así tranformamos un diccionario en una tabla de Pandas
data1

      nombre  edad  salario    ciudad
0      Aaron  25.0   1500.0    Bogotá
1      Luisa   NaN   2100.0  Medellín
2  Sebastian  32.0      NaN      Cali
3        Ana  24.0   1200.0    Bogotá
4       None  45.0   5500.0      Cali

In [98]:
data1.isnull() #Valores Faltantes
#El médoto isnull, muestra true si el valor es faltante y false si el valor no es faltante

   nombre   edad  salario  ciudad
0   False  False    False   False
1   False   True    False   False
2   False  False     True   False
3   False  False    False   False
4    True  False    False   False

In [99]:
data1.isnull().sum() #El método sum, suma los valores por columnas: 1 si es faltante, 0 si no.

nombre     1
edad       1
salario    1
ciudad     0
dtype: int64

In [100]:
data2 = data1.dropna() #El modelo Dropna, elimina las filas con valores faltantes
data2

  nombre  edad  salario  ciudad
0  Aaron  25.0   1500.0  Bogotá
3    Ana  24.0   1200.0  Bogotá

In [101]:
data1.dropna(subset=['salario']) #Se eliminan las filas con valores faltantes, únicamente
#en la columna salario

  nombre  edad  salario    ciudad
0  Aaron  25.0   1500.0    Bogotá
1  Luisa   NaN   2100.0  Medellín
3    Ana  24.0   1200.0    Bogotá
4   None  45.0   5500.0      Cali

In [102]:
data1['edad'] = data1['edad'].fillna(data1['edad'].mean())
data1['nombre'] = data1['nombre'].fillna('Desconocido')
data1
#Se están imputando datos faltantes, es decir que ponga la media aritmética de la columna de edad de data1
#Con la columna nombre la esta reemplazando con la misma columna nombre, pero a los valores faltantes les pone desconocido

        nombre  edad  salario    ciudad
0        Aaron  25.0   1500.0    Bogotá
1        Luisa  31.5   2100.0  Medellín
2    Sebastian  32.0      NaN      Cali
3          Ana  24.0   1200.0    Bogotá
4  Desconocido  45.0   5500.0      Cali

In [103]:
data1['ciudad'] = data1['ciudad'].replace('Bogotá', 'BOGOTA')
data1
#El modelo replace o reemplazo, lo que hace es reemplazar la palabra Bogotá por BOGOTA en Mayúscula, en la columna ciudad
#de data1

        nombre  edad  salario    ciudad
0        Aaron  25.0   1500.0    BOGOTA
1        Luisa  31.5   2100.0  Medellín
2    Sebastian  32.0      NaN      Cali
3          Ana  24.0   1200.0    BOGOTA
4  Desconocido  45.0   5500.0      Cali

In [104]:
data4 = data1['ciudad'].drop_duplicates()
data4
#Se toma data1 sin duplicados

0      BOGOTA
1    Medellín
2        Cali
Name: ciudad, dtype: object

In [ ]:
data5 = {
    'nombre': ['Ana', 'Luis', 'Ana', 'Carlos', 'Luis'],
        'edad': [23, 30, 23, 35, 30],
        'ciudad': ['Bogotá', 'Cali', 'Bogotá', 'Medellín', 'Cali']
    }
data5 = pd.DataFrame(data5)
data5

   nombre  edad    ciudad
0     Ana    23    Bogotá
1    Luis    30      Cali
2     Ana    23    Bogotá
3  Carlos    35  Medellín
4    Luis    30      Cali

In [ ]:
data6 = data5.drop_duplicates()
data6
#Aquellos valores que tengang duplicados, pues no los considera

   nombre  edad    ciudad
0     Ana    23    Bogotá
1    Luis    30      Cali
3  Carlos    35  Medellín

In [105]:
dfn = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'nombre': ['Aaron', 'Luisa', 'Sebastian', 'ana'],
        'edad': [23, 30, 35, 28],
        'salario': [1000, 2000, 3000, 1500],
        'ciudad': ['Bogotá', 'Cali', 'Bogotá', 'Medellín']
    })
dfn

   id     nombre  edad  salario    ciudad
0   1      Aaron    23     1000    Bogotá
1   2      Luisa    30     2000      Cali
2   3  Sebastian    35     3000    Bogotá
3   4        ana    28     1500  Medellín

In [106]:
dfn['salario_anual'] = dfn['salario'] * 12 #aplicar función
dfn['edad_doble'] = dfn['edad'].apply(lambda x: x * 2)
dfn
#Estamos agregando una nueva columna: una que es el salario anual y la otra que es el doble de la edad

   id     nombre  edad  salario    ciudad  salario_anual  edad_doble
0   1      Aaron    23     1000    Bogotá          12000          46
1   2      Luisa    30     2000      Cali          24000          60
2   3  Sebastian    35     3000    Bogotá          36000          70
3   4        ana    28     1500  Medellín          18000          56

In [107]:
dfn = dfn.rename(columns= {'edad': 'age'}) #Renombrar columnas, entonces la columna edad la renombra como edad en inglés
dfn

   id     nombre  age  salario    ciudad  salario_anual  edad_doble
0   1      Aaron   23     1000    Bogotá          12000          46
1   2      Luisa   30     2000      Cali          24000          60
2   3  Sebastian   35     3000    Bogotá          36000          70
3   4        ana   28     1500  Medellín          18000          56

In [108]:
dfn['nombre'] = dfn['nombre'].str.upper() #Convierte al objeto en letras mayúsculas como son las cadenas del nombre
dfn['nombre'] = dfn['nombre'].str.strip() #Limpia las cadenas del nombre y eliminando los espacios en blanco
dfn['nombre'] = dfn['nombre'].str.replace('ANA', 'JANA') #Replace reemplaza a ana por ANA

In [109]:
dfn

   id     nombre  age  salario    ciudad  salario_anual  edad_doble
0   1      AARON   23     1000    Bogotá          12000          46
1   2      LUISA   30     2000      Cali          24000          60
2   3  SEBASTIAN   35     3000    Bogotá          36000          70
3   4       JANA   28     1500  Medellín          18000          56

In [110]:
grupo = dfn.groupby('ciudad')['salario'].mean()
grupo
#Este método toma la columna ciudad y todos los elementos de la columna salario, para calcular la media aritmética del salario
#Agrupa todos los elementos de ciudad y calcula a esos grupos la media aritmética

ciudad
Bogotá      2000.0
Cali        2000.0
Medellín    1500.0
Name: salario, dtype: float64

In [111]:
ordenado = dfn.sort_values(by= 'age')
ordenado
#Ordenar los datos de la base de datos

   id     nombre  age  salario    ciudad  salario_anual  edad_doble
0   1      AARON   23     1000    Bogotá          12000          46
3   4       JANA   28     1500  Medellín          18000          56
1   2      LUISA   30     2000      Cali          24000          60
2   3  SEBASTIAN   35     3000    Bogotá          36000          70

In [112]:
dfn1 = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'departamento': ['Ventas', 'IT', 'RRHH', 'Marketing']
    })

merge = pd.merge(dfn, dfn1, on= 'id')
merge

,id,nombre,age,salario,ciudad,salario_anual,edad_doble,departamento
0,1,AARON,23,1000,Bogotá,12000,46,Ventas
1,2,LUISA,30,2000,Cali,24000,60,IT
2,3,SEBASTIAN,35,3000,Bogotá,36000,70,RRHH
3,4,JANA,28,1500,Medellín,18000,56,Marketing

In [113]:
valores = dfn.values
valores
#Sí se quiere cambiar un objeto tipo Pandas a un objeto tipo NumPy, usamos el método values

array([[1, 'AARON', 23, 1000, 'Bogotá', 12000, 46],
       [2, 'LUISA', 30, 2000, 'Cali', 24000, 60],
       [3, 'SEBASTIAN', 35, 3000, 'Bogotá', 36000, 70],
       [4, 'JANA', 28, 1500, 'Medellín', 18000, 56]], dtype=object)

In [114]:
arr = np.array([10, 20, 30])
df = pd.DataFrame(arr)
df
#Sí se quiere cambiar un objeto tipo NumPy a un objeto tipo Pandas, usamos el método DataFrame

    0
0  10
1  20
2  30